name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type check
        run: npx tsc --noEmit

  tests:
    runs-on: ubuntu-latest
    needs: typecheck # runs only after typecheck finishes successfully

    # Start a temporary PostgreSQL service
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run migrations to prepare the test DB
        env:
          DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb
        run: npm run prisma:migrate

      - name: Run tests with verbose output
        env:
          DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb
        run: npm run test:verbose
